[build]
  publish = "dist"
  command = "npm run build"
  functions = "netlify/functions"

[dev]
  framework = "#auto"
  functions = "netlify/functions"

# Handle client-side routing (for React Router)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200